    
InicializarLibro();
    InicializarLibro(1, "To Kill a Mockingbird", "Harper Lee", 15.99, FICTION, 10)
    InicializarLibro(2, "1984", "George Orwell", 12.49, FICTION, 5)
    InicializarLibro(3, "The Great Gatsby", "F. Scott Fitzgerald", 10.99, FICTION, 8)
    InicializarLibro(4, "Moby Dick", "Herman Melville", 18.99, FICTION, 12)
    InicializarLibro(5, "War and Peace", "Leo Tolstoy", 20.00, FICTION, 7)
    InicializarLibro(6, "Pride and Prejudice", "Jane Austen", 14.99, FICTION, 9)
    InicializarLibro(7, "The Catcher in the Rye", "J.D. Salinger", 10.00, FICTION, 6)
    InicializarLibro(8, "The Odyssey", "Homer", 17.49, FICTION, 4)
    InicializarLibro(9, "Ulysses", "James Joyce", 25.00, FICTION, 2)
    InicializarLibro(10, "The Divine Comedy", "Dante Alighieri", 22.00, POETRY, 3)
    InicializarLibro(11, "Leaves of Grass", "Walt Whitman", 13.00, POETRY, 11)
    InicializarLibro(12, "The Iliad", "Homer", 18.50, FICTION, 7),
    InicializarLibro(13, "A Brief History of Time", "Stephen Hawking", 15.00, NON_FICTION, 15)
    InicializarLibro(14, "The Art of War", "Sun Tzu", 9.99, NON_FICTION, 20)
    InicializarLibro(15, "Sapiens: A Brief History of Humankind", "Yuval Noah Harari", 16.49, NON_FICTION, 13)
    InicializarLibro(16, "The Selfish Gene", "Richard Dawkins", 14.00, NON_FICTION, 6)
    InicializarLibro(17, "The Road to Serfdom", "F.A. Hayek", 10.50, NON_FICTION, 5)
    InicializarLibro(18, "The Wealth of Nations", "Adam Smith", 30.00, NON_FICTION, 8)
    InicializarLibro(19, "On the Origin of Species", "Charles Darwin", 24.99, NON_FICTION, 4)
    InicializarLibro(20, "The Prince", "Niccolò Machiavelli", 8.99, NON_FICTION, 14)
    InicializarLibro(21, "Hamlet", "William Shakespeare", 11.50, THEATER, 6)
    InicializarLibro(22, "Macbeth", "William Shakespeare", 9.50, THEATER, 8)
    InicializarLibro(23, "Othello", "William Shakespeare", 10.99, THEATER, 7)
    InicializarLibro(24, "A Doll's House", "Henrik Ibsen", 12.50, THEATER, 5)
    InicializarLibro(25, "Waiting for Godot", "Samuel Beckett", 13.99, THEATER, 4)
    InicializarLibro(26, "Death of a Salesman", "Arthur Miller", 14.99, THEATER, 10)
    InicializarLibro(27, "The Glass Menagerie", "Tennessee Williams", 11.00, THEATER, 9)
    InicializarLibro(28, "Long Day's Journey into Night", "Eugene O'Neill", 19.50, THEATER, 3)
    InicializarLibro(29, "The Importance of Being Earnest", "Oscar Wilde", 8.50, THEATER, 15)
    InicializarLibro(30, "The Waste Land", "T.S. Eliot", 6.99, POETRY, 10)
    InicializarLibro(31, "Paradise Lost", "John Milton", 12.00, POETRY, 7)
    InicializarLibro(32, "Beowulf", "Anonymous", 15.00, POETRY, 5)
    InicializarLibro(33, "Essays", "Michel de Montaigne", 20.00, ESSAY, 4)
    InicializarLibro(34, "Self-Reliance and Other Essays", "Ralph Waldo Emerson", 9.00, ESSAY, 9)
    InicializarLibro(35, "Civil Disobedience and Other Essays", "Henry David Thoreau", 7.50, ESSAY, 11)
    InicializarLibro(36, "Meditations", "Marcus Aurelius", 11.99, ESSAY, 8)
    InicializarLibro(37, "The Federalist Papers", "Alexander Hamilton, James Madison, John Jay", 18.00, ESSAY, 5)
    InicializarLibro(38, "The Communist Manifesto", "Karl Marx and Friedrich Engels", 5.99, ESSAY, 12)
    InicializarLibro(39, "The Republic", "Plato", 16.00, ESSAY, 6)
    InicializarLibro(40, "Thus Spoke Zarathustra", "Friedrich Nietzsche", 14.99, ESSAY, 10)